apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  type: LoadBalancer
  selector:
    name: locust-master
    role: master  
  ports:
    - port: 8089
      protocol: TCP
      name: master-web
    - port: 5557
      protocol: TCP
      name: master-port-1
    - port: 5558
      protocol: TCP
      name: master-port-2