apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: locust-worker
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50